In [1]:
from playerPredictor import get_team_player_scores, identify_nba_season
from teamPredictor import calculate_net_four, calculate_recent_form_scores
# identify_nba_season('12/22/2020')

In [3]:
def compute_team_strength_score(engine, date, team_name):
    # compute team performance scores
    recent_form = calculate_recent_form_scores(engine, date, team_name)
    season_net, season_four_factors = calculate_net_four(engine, date, team_name)

    team_performance = (0.7 * recent_form) + (0.3 * (0.5 * season_net + 0.5 * season_four_factors))

    # computer player contribution score
    player_scores_df = get_team_player_scores(engine, team_name, date)

    star_players = player_scores_df[player_scores_df["CATEGORY"] == "Star"]
    rotation_players = player_scores_df[player_scores_df["CATEGORY"] == "Rotation"]

    star_score = star_players["SCORE"].mean()
    rotation_score = rotation_players["SCORE"].mean()

    player_contribution = (0.7 * star_score) + (0.3 * rotation_score)

    # Computer Historical Matchup Scores
    # historical_matchups = calculate_historic_matchups(engine, date, team_name, opponent_team, avg_games=3, weighted=True)

    # historical_matchup_score = (0.5 * historical_matchups['net_rating_diff']) + \
    #                            (0.3 * historical_matchups['efg_diff']) + \
    #                            (0.2 * historical_matchups['turnover_pct_diff'])

    TSS = (0.5 * team_performance) + (0.5 * player_contribution)  # + (0.15 * historical_matchup_score)
    return TSS

In [27]:
import os
from datetime import datetime, timedelta

import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)
team_name = "Detroit Pistons"


# date = '03-13-2023'
# date = '2024-12-13'
# compute_team_strength_score(engine, date, team_name)
def track_team_strength_over_time(
    engine,
    team_name,
    start_date_str="2023-11-01",
    end_date_str="2024-03-01",
    step_days=5,
    season_start_dates=None,
):
    if season_start_dates is None:
        season_start_dates = {
            "2020-21": "2020-12-22",
            "2021-22": "2021-10-19",
            "2022-23": "2022-10-18",
            "2023-24": "2023-10-24",
            "2024-25": "2024-10-22",
        }

    # Convert date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")

    # Initialize results list to store data
    results = []

    # Initialize current date
    current_date = start_date

    print(f"Analyzing {team_name} strength from {start_date_str} to {end_date_str} every {step_days} days...")

    # Loop through dates
    while current_date <= end_date:
        try:
            # Format date for the compute_team_strength_score function
            date_str = current_date.strftime("%Y-%m-%d")

            print(f"Computing strength score for {team_name} on {date_str}...")

            # Compute team strength score
            strength_score = compute_team_strength_score(engine, date_str, team_name)

            # Get NBA season for the date
            season = identify_nba_season(date_str)

            # Store result
            results.append(
                {
                    "Team": team_name,
                    "Date": date_str,
                    "Strength_Score": strength_score,
                    "Season": season,
                }
            )

            print(f"  Score: {strength_score:.4f}")

        except Exception as e:
            print(f"Error computing strength score for {date_str}: {e}")
            # Add a row with error information
            results.append(
                {
                    "Team": team_name,
                    "Date": date_str,
                    "Strength_Score": None,
                    "Season": identify_nba_season(date_str),
                    "Error": str(e),
                }
            )

        # Move to next date
        current_date += timedelta(days=step_days)

    # Convert results to DataFrame
    results_df = pd.DataFrame(results)

    # Display summary
    if not results_df.empty:
        print("\nSummary Statistics:")
        print(f"Mean Strength Score: {results_df['Strength_Score'].mean():.4f}")
        print(f"Min Strength Score: {results_df['Strength_Score'].min():.4f}")
        print(f"Max Strength Score: {results_df['Strength_Score'].max():.4f}")

    return results_df

In [41]:
start_date_str = "2023-11-01"
end_date_str = "2024-03-01"
# Convert date strings to datetime objects
start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
print(start_date)
print(end_date)
date_str = start_date.strftime("%Y-%m-%d")
print(date_str)

2023-11-01 00:00:00
2024-03-01 00:00:00
2023-11-01

In [45]:
import os

from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)
team_name = "Detroit Pistons"
results = track_team_strength_over_time(
    engine, team_name, start_date_str="2024-11-01", end_date_str="2025-03-01", step_days=5
)
results

Analyzing Detroit Pistons strength from 2024-11-01 to 2025-03-01 every 5 days...
Computing strength score for Detroit Pistons on 2024-11-01...
Error computing strength score for 2024-11-01: list index out of range
Computing strength score for Detroit Pistons on 2024-11-06...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-06: list index out of range
Computing strength score for Detroit Pistons on 2024-11-11...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-11: list index out of range
Computing strength score for Detroit Pistons on 2024-11-16...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-16: list index out of range
Computing strength score for Detroit Pistons on 2024-11-21...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 2.652
Recent Four Factors Score: 0.492404

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.9562499999999998
Recent Four Factors Score: -3.6066191176470586
  Score: 1.6777
Computing strength score for Detroit Pistons on 2024-11-26...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 2.2279999999999998
Recent Four Factors Score: 0.48996999999999996

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.8411764705882351
Recent Four Factors Score: -3.586394582043343
  Score: 1.5602
Computing strength score for Detroit Pistons on 2024-12-01...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.9319999999999999
Recent Four Factors Score: 0.49860499999999996

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -1.3000000000000003
Recent Four Factors Score: -3.636095
  Score: 0.6700
Computing strength score for Detroit Pistons on 2024-12-06...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -5.536
Recent Four Factors Score: 0.506142

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.6772727272727277
Recent Four Factors Score: -3.666030113636364
  Score: -0.6457
Computing strength score for Detroit Pistons on 2024-12-11...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -3.226
Recent Four Factors Score: 0.5195620000000001

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.273913043478261
Recent Four Factors Score: -3.6820086086956527
  Score: -0.0360
Computing strength score for Detroit Pistons on 2024-12-16...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -7.886000000000001
Recent Four Factors Score: 0.5152329999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -3.096
Recent Four Factors Score: -3.6143831111111115
  Score: -1.3998
Computing strength score for Detroit Pistons on 2024-12-21...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -4.776
Recent Four Factors Score: 0.5229459999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.7370370370370374
Recent Four Factors Score: -3.5083360791826315
  Score: -0.5349
Computing strength score for Detroit Pistons on 2024-12-26...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.852
Recent Four Factors Score: 0.5243289999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.3689655172413793
Recent Four Factors Score: -3.4188373192436043
  Score: -0.0199
Computing strength score for Detroit Pistons on 2024-12-31...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -3.8259999999999996
Recent Four Factors Score: 0.526819

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.756666666666667
Recent Four Factors Score: -3.3850881250000002
  Score: -0.3058
Computing strength score for Detroit Pistons on 2025-01-05...
Net Rating Score: 0.9439999999999997
Recent Four Factors Score: 0.5103759999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -1.6818181818181819
Recent Four Factors Score: -3.4355772294372295
  Score: 1.0363
Computing strength score for Detroit Pistons on 2025-01-10...
Net Rating Score: 5.517999999999999
Recent Four Factors Score: 0.513355

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -1.0444444444444445
Recent Four Factors Score: -3.4277489766081874
  Score: 2.3282
Computing strength score for Detroit Pistons on 2025-01-15...
Net Rating Score: 5.318000000000001
Recent Four Factors Score: 0.521153

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.6210526315789471
Recent Four Factors Score: -3.413582434210527
  Score: 2.3399
Computing strength score for Detroit Pistons on 2025-01-20...
Net Rating Score: 3.2600000000000007
Recent Four Factors Score: 0.510577

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.724390243902439
Recent Four Factors Score: -3.4319493760635282
  Score: 1.7823
Computing strength score for Detroit Pistons on 2025-01-25...
Net Rating Score: 1.578
Recent Four Factors Score: 0.505617

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.6046511627906976
Recent Four Factors Score: -3.4511758914728685
  Score: 1.3442
Computing strength score for Detroit Pistons on 2025-01-30...
Net Rating Score: -2.7319999999999998
Recent Four Factors Score: 0.499

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -1.2755555555555558
Recent Four Factors Score: -3.4164302600472816
  Score: 0.1519
Computing strength score for Detroit Pistons on 2025-02-04...
Net Rating Score: -1.6140000000000003
Recent Four Factors Score: 0.50449

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.7604166666666665
Recent Four Factors Score: -3.3285194166666674
  Score: 0.4809
Computing strength score for Detroit Pistons on 2025-02-09...
Net Rating Score: 3.6819999999999986
Recent Four Factors Score: 0.5159039999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -0.21568627450980393
Recent Four Factors Score: -3.291840344062153
  Score: 1.9228
Computing strength score for Detroit Pistons on 2025-02-14...
Net Rating Score: 11.004000000000001
Recent Four Factors Score: 0.521965

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 0.8792452830188684
Recent Four Factors Score: -3.2906969125214416
  Score: 3.9556
Computing strength score for Detroit Pistons on 2025-02-19...
Net Rating Score: 11.004000000000001
Recent Four Factors Score: 0.521965

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 0.8792452830188684
Recent Four Factors Score: -3.2906969125214416
  Score: 3.9800
Computing strength score for Detroit Pistons on 2025-02-24...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 13.748000000000001
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 1.098181818181818
Recent Four Factors Score: nan
  Score: nan
Computing strength score for Detroit Pistons on 2025-03-01...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 13.748000000000001
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 1.098181818181818
Recent Four Factors Score: nan
  Score: nan

Summary Statistics:
Mean Strength Score: 1.0678
Min Strength Score: -1.3998
Max Strength Score: 3.9800

,Team,Date,Strength_Score,Season,Error
0,Detroit Pistons,2024-11-01,NaN,2024-25,list index out of range
1,Detroit Pistons,2024-11-06,NaN,2024-25,list index out of range
2,Detroit Pistons,2024-11-11,NaN,2024-25,list index out of range
3,Detroit Pistons,2024-11-16,NaN,2024-25,list index out of range
4,Detroit Pistons,2024-11-21,1.677744,2024-25,NaN
5,Detroit Pistons,2024-11-26,1.560229,2024-25,NaN
6,Detroit Pistons,2024-12-01,0.669956,2024-25,NaN
7,Detroit Pistons,2024-12-06,-0.645692,2024-25,NaN
8,Detroit Pistons,2024-12-11,-0.036002,2024-25,NaN
9,Detroit Pistons,2024-12-16,-1.399784,2024-25,NaN
10,Detroit Pistons,2024-12-21,-0.534863,2024-25,NaN
11,Detroit Pistons,2024-12-26,-0.019892,2024-25,NaN
12,Detroit Pistons,2024-12-31,-0.305808,2024-25,NaN
13,Detroit Pistons,2025-01-05,1.036316,2024-25,NaN
14,Detroit Pistons,2025-01-10,2.328246,2024-25,NaN
15,Detroit Pistons,2025-01-15,2.339911,2024-25,NaN
16,Detroit Pistons,2025-01-20,1.782291,2024-25,NaN
17,Detroit Pistons,2025-01-25,1.344235,2024-25,NaN
18,Detroit Pistons,2025-01-30,0.151860,2024-25,NaN
19,Detroit Pistons,2025-02-04,0.480916,2024-25,NaN
20,Detroit Pistons,2025-02-09,1.922844,2024-25,NaN
21,Detroit Pistons,2025-02-14,3.955554,2024-25,NaN
22,Detroit Pistons,2025-02-19,3.979995,2024-25,NaN
23,Detroit Pistons,2025-02-24,NaN,2024-25,NaN
24,Detroit Pistons,2025-03-01,NaN,2024-25,NaN

In [47]:
import os

from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)
team_name = "Atlanta Hawks"
results_2 = track_team_strength_over_time(
    engine, team_name, start_date_str="2024-11-01", end_date_str="2025-03-01", step_days=5
)
results_2

Analyzing Atlanta Hawks strength from 2024-11-01 to 2025-03-01 every 5 days...
Computing strength score for Atlanta Hawks on 2024-11-01...
Error computing strength score for 2024-11-01: list index out of range
Computing strength score for Atlanta Hawks on 2024-11-06...
Error computing strength score for 2024-11-06: list index out of range
Computing strength score for Atlanta Hawks on 2024-11-11...
Error computing strength score for 2024-11-11: list index out of range
Computing strength score for Atlanta Hawks on 2024-11-16...
Error computing strength score for 2024-11-16: list index out of range
Computing strength score for Atlanta Hawks on 2024-11-21...
Net Rating Score: -3.062
Recent Four Factors Score: 0.48753500000000005
Net Rating Score: -4.65625
Recent Four Factors Score: -3.390959375
  Score: -0.0213
Computing strength score for Atlanta Hawks on 2024-11-26...
Net Rating Score: -6.394
Recent Four Factors Score: 0.48779600000000006
Net Rating Score: -5.466666666666667
Recent Four Factors Score: -3.2671305555555556
  Score: -0.9680
Computing strength score for Atlanta Hawks on 2024-12-01...
Net Rating Score: 0.4820000000000001
Recent Four Factors Score: 0.5084949999999999
Net Rating Score: -3.142857142857143
Recent Four Factors Score: -3.4013000000000004
  Score: 1.1411
Computing strength score for Atlanta Hawks on 2024-12-06...
Net Rating Score: 4.838000000000001
Recent Four Factors Score: 0.5141169999999999
Net Rating Score: -1.6499999999999997
Recent Four Factors Score: -3.3777541666666675
  Score: 2.4314
Computing strength score for Atlanta Hawks on 2024-12-11...
Net Rating Score: 1.266
Recent Four Factors Score: 0.5044620000000001
Net Rating Score: -2.3307692307692305
Recent Four Factors Score: -3.2940749999999994
  Score: 1.4409
Computing strength score for Atlanta Hawks on 2024-12-16...
Net Rating Score: 0.264
Recent Four Factors Score: 0.49621000000000004
Net Rating Score: -2.4925925925925925
Recent Four Factors Score: -3.269840740740741
  Score: 1.1308
Computing strength score for Atlanta Hawks on 2024-12-21...
Net Rating Score: -3.65
Recent Four Factors Score: 0.49173100000000003
Net Rating Score: -2.962068965517241
Recent Four Factors Score: -3.3733724137931036
  Score: 0.0679
Computing strength score for Atlanta Hawks on 2024-12-26...
Net Rating Score: -0.5439999999999998
Recent Four Factors Score: 0.514173
Net Rating Score: -2.1548387096774193
Recent Four Factors Score: -3.404424193548387
  Score: 0.9101
Computing strength score for Atlanta Hawks on 2024-12-31...
Net Rating Score: 4.0840000000000005
Recent Four Factors Score: 0.522598
Net Rating Score: -0.8757575757575758
Recent Four Factors Score: -3.3677954545454556
  Score: 2.2873
Computing strength score for Atlanta Hawks on 2025-01-05...
Net Rating Score: -3.2279999999999998
Recent Four Factors Score: 0.501619
Net Rating Score: -2.422222222222222
Recent Four Factors Score: -3.334715277777777
  Score: 0.2457
Computing strength score for Atlanta Hawks on 2025-01-10...
Net Rating Score: -6.5360000000000005
Recent Four Factors Score: 0.508947
Net Rating Score: -2.4684210526315793
Recent Four Factors Score: -3.2690526315789463
  Score: -0.6648
Computing strength score for Atlanta Hawks on 2025-01-15...
Net Rating Score: -0.5719999999999996
Recent Four Factors Score: 0.507569
Net Rating Score: -1.8249999999999997
Recent Four Factors Score: -3.230856249999999
  Score: 0.9434
Computing strength score for Atlanta Hawks on 2025-01-20...
Net Rating Score: -0.6959999999999994
Recent Four Factors Score: 0.496447
Net Rating Score: -1.8190476190476188
Recent Four Factors Score: -3.2954928571428557
  Score: 0.9271
Computing strength score for Atlanta Hawks on 2025-01-25...
Net Rating Score: -5.744
Recent Four Factors Score: 0.47964200000000007
Net Rating Score: -2.4644444444444447
Recent Four Factors Score: -3.3163866666666655
  Score: -0.4412
Computing strength score for Atlanta Hawks on 2025-01-30...
Net Rating Score: -7.788
Recent Four Factors Score: 0.467868
Net Rating Score: -3.0166666666666657
Recent Four Factors Score: -3.3370802083333335
  Score: -1.0477
Computing strength score for Atlanta Hawks on 2025-02-04...
Net Rating Score: -7.090000000000002
Recent Four Factors Score: 0.486013
Net Rating Score: -2.9059999999999993
Recent Four Factors Score: -3.309647
  Score: -0.8592
Computing strength score for Atlanta Hawks on 2025-02-09...
Net Rating Score: -1.0819999999999999
Recent Four Factors Score: 0.5103869999999999
Net Rating Score: -2.4
Recent Four Factors Score: -3.282287735849057
  Score: 0.7642
Computing strength score for Atlanta Hawks on 2025-02-14...
Net Rating Score: 0.8760000000000001
Recent Four Factors Score: 0.515456
Net Rating Score: -2.2600000000000007
Recent Four Factors Score: -3.273343636363636
  Score: 1.3012
Computing strength score for Atlanta Hawks on 2025-02-19...
Net Rating Score: 0.8760000000000001
Recent Four Factors Score: 0.515456
Net Rating Score: -2.2600000000000007
Recent Four Factors Score: -3.273343636363636
  Score: 1.2280
Computing strength score for Atlanta Hawks on 2025-02-24...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 0.526
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.2877192982456136
Recent Four Factors Score: nan
  Score: nan
Computing strength score for Atlanta Hawks on 2025-03-01...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 0.526
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: -2.2877192982456136
Recent Four Factors Score: nan
  Score: nan

Summary Statistics:
Mean Strength Score: 0.5693
Min Strength Score: -1.0477
Max Strength Score: 2.4314

,Team,Date,Strength_Score,Season,Error
0,Atlanta Hawks,2024-11-01,NaN,2024-25,list index out of range
1,Atlanta Hawks,2024-11-06,NaN,2024-25,list index out of range
2,Atlanta Hawks,2024-11-11,NaN,2024-25,list index out of range
3,Atlanta Hawks,2024-11-16,NaN,2024-25,list index out of range
4,Atlanta Hawks,2024-11-21,-0.021336,2024-25,NaN
5,Atlanta Hawks,2024-11-26,-0.968036,2024-25,NaN
6,Atlanta Hawks,2024-12-01,1.141123,2024-25,NaN
7,Atlanta Hawks,2024-12-06,2.431382,2024-25,NaN
8,Atlanta Hawks,2024-12-11,1.440873,2024-25,NaN
9,Atlanta Hawks,2024-12-16,1.130751,2024-25,NaN
10,Atlanta Hawks,2024-12-21,0.067941,2024-25,NaN
11,Atlanta Hawks,2024-12-26,0.910102,2024-25,NaN
12,Atlanta Hawks,2024-12-31,2.287332,2024-25,NaN
13,Atlanta Hawks,2025-01-05,0.245656,2024-25,NaN
14,Atlanta Hawks,2025-01-10,-0.664778,2024-25,NaN
15,Atlanta Hawks,2025-01-15,0.943383,2024-25,NaN
16,Atlanta Hawks,2025-01-20,0.927095,2024-25,NaN
17,Atlanta Hawks,2025-01-25,-0.441186,2024-25,NaN
18,Atlanta Hawks,2025-01-30,-1.047734,2024-25,NaN
19,Atlanta Hawks,2025-02-04,-0.859161,2024-25,NaN
20,Atlanta Hawks,2025-02-09,0.764158,2024-25,NaN
21,Atlanta Hawks,2025-02-14,1.301150,2024-25,NaN
22,Atlanta Hawks,2025-02-19,1.228043,2024-25,NaN
23,Atlanta Hawks,2025-02-24,NaN,2024-25,NaN
24,Atlanta Hawks,2025-03-01,NaN,2024-25,NaN

In [49]:
import os

from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)
team_name = "Cleveland Cavaliers"
results_2 = track_team_strength_over_time(
    engine, team_name, start_date_str="2024-11-01", end_date_str="2025-03-01", step_days=5
)
results_2

Analyzing Cleveland Cavaliers strength from 2024-11-01 to 2025-03-01 every 5 days...
Computing strength score for Cleveland Cavaliers on 2024-11-01...
Error computing strength score for 2024-11-01: list index out of range
Computing strength score for Cleveland Cavaliers on 2024-11-06...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-06: list index out of range
Computing strength score for Cleveland Cavaliers on 2024-11-11...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-11: list index out of range
Computing strength score for Cleveland Cavaliers on 2024-11-16...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Error computing strength score for 2024-11-16: list index out of range
Computing strength score for Cleveland Cavaliers on 2024-11-21...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.309999999999999
Recent Four Factors Score: 0.558915

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.775
Recent Four Factors Score: -2.663836764705883
  Score: 5.0833
Computing strength score for Cleveland Cavaliers on 2024-11-26...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.850000000000001
Recent Four Factors Score: 0.5569050000000001

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.952941176470588
Recent Four Factors Score: -2.676648529411765
  Score: 5.4009
Computing strength score for Cleveland Cavaliers on 2024-12-01...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 5.496
Recent Four Factors Score: 0.527345

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 9.105
Recent Four Factors Score: -2.7264657142857143
  Score: 3.4511
Computing strength score for Cleveland Cavaliers on 2024-12-06...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 7.069999999999999
Recent Four Factors Score: 0.521544

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.181818181818182
Recent Four Factors Score: -2.7278974308300397
  Score: 3.9428
Computing strength score for Cleveland Cavaliers on 2024-12-11...
Net Rating Score: 8.937999999999999
Recent Four Factors Score: 0.522845

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 9.745833333333334
Recent Four Factors Score: -2.6879168333333334
  Score: 4.4181
Computing strength score for Cleveland Cavaliers on 2024-12-16...
Net Rating Score: 9.498
Recent Four Factors Score: 0.520752

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.396153846153847
Recent Four Factors Score: -2.7100226495726494
  Score: 4.5386
Computing strength score for Cleveland Cavaliers on 2024-12-21...
Net Rating Score: 14.378
Recent Four Factors Score: 0.529384

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.510714285714286
Recent Four Factors Score: -2.7476275862068964
  Score: 5.9218
Computing strength score for Cleveland Cavaliers on 2024-12-26...
Net Rating Score: 17.230000000000004
Recent Four Factors Score: 0.532638

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.455172413793106
Recent Four Factors Score: -2.7123481034482753
  Score: 6.7296
Computing strength score for Cleveland Cavaliers on 2024-12-31...
Net Rating Score: 15.374
Recent Four Factors Score: 0.5409479999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.665625
Recent Four Factors Score: -2.689826704545454
  Score: 6.2602
Computing strength score for Cleveland Cavaliers on 2025-01-05...
Net Rating Score: 14.508
Recent Four Factors Score: 0.538868

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.579411764705881
Recent Four Factors Score: -2.643893613445377
  Score: 6.0348
Computing strength score for Cleveland Cavaliers on 2025-01-10...
Net Rating Score: 11.662
Recent Four Factors Score: 0.5446420000000001

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 11.266666666666666
Recent Four Factors Score: -2.6460012762762752
  Score: 5.2688
Computing strength score for Cleveland Cavaliers on 2025-01-15...
Net Rating Score: 5.892
Recent Four Factors Score: 0.5320039999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.528947368421052
Recent Four Factors Score: -2.6627309716599186
  Score: 3.7027
Computing strength score for Cleveland Cavaliers on 2025-01-20...
Net Rating Score: 4.015999999999999
Recent Four Factors Score: 0.525425

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.129268292682926
Recent Four Factors Score: -2.653847648083622
  Score: 3.1489
Computing strength score for Cleveland Cavaliers on 2025-01-25...
Net Rating Score: 2.3379999999999996
Recent Four Factors Score: 0.5257749999999999

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 9.136363636363635
Recent Four Factors Score: -2.6643518181818173
  Score: 2.6496
Computing strength score for Cleveland Cavaliers on 2025-01-30...
Net Rating Score: 8.134
Recent Four Factors Score: 0.544266

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 9.827659574468083
Recent Four Factors Score: -2.61324222074468
  Score: 4.2134
Computing strength score for Cleveland Cavaliers on 2025-02-04...
Net Rating Score: 14.693999999999999
Recent Four Factors Score: 0.542578

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.144897959183671
Recent Four Factors Score: -2.5939980204081627
  Score: 5.9820
Computing strength score for Cleveland Cavaliers on 2025-02-09...
Net Rating Score: 10.986
Recent Four Factors Score: 0.541064

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 9.976470588235292
Recent Four Factors Score: -2.654275622171946
  Score: 4.9950
Computing strength score for Cleveland Cavaliers on 2025-02-14...
Net Rating Score: 12.374
Recent Four Factors Score: 0.536251

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.40943396226415
Recent Four Factors Score: -2.670500995807128
  Score: 5.4079
Computing strength score for Cleveland Cavaliers on 2025-02-19...
Net Rating Score: 12.374
Recent Four Factors Score: 0.536251

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.40943396226415
Recent Four Factors Score: -2.670500995807128
  Score: 5.4292
Computing strength score for Cleveland Cavaliers on 2025-02-24...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 16.870000000000005
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.723214285714286
Recent Four Factors Score: nan
  Score: nan
Computing strength score for Cleveland Cavaliers on 2025-03-01...

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:178: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 16.870000000000005
Recent Four Factors Score: nan

C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)
C:\Users\Chase\ML Algorithm\JupyterScrapers\predictionScripts\teamPredictor.py:364: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  games_df = pd.concat([games_df, individual_team_df], ignore_index=True)

Net Rating Score: 10.723214285714286
Recent Four Factors Score: nan
  Score: nan

Summary Statistics:
Mean Strength Score: 4.8726
Min Strength Score: 2.6496
Max Strength Score: 6.7296

,Team,Date,Strength_Score,Season,Error
0,Cleveland Cavaliers,2024-11-01,NaN,2024-25,list index out of range
1,Cleveland Cavaliers,2024-11-06,NaN,2024-25,list index out of range
2,Cleveland Cavaliers,2024-11-11,NaN,2024-25,list index out of range
3,Cleveland Cavaliers,2024-11-16,NaN,2024-25,list index out of range
4,Cleveland Cavaliers,2024-11-21,5.083306,2024-25,NaN
5,Cleveland Cavaliers,2024-11-26,5.400863,2024-25,NaN
6,Cleveland Cavaliers,2024-12-01,3.451137,2024-25,NaN
7,Cleveland Cavaliers,2024-12-06,3.942833,2024-25,NaN
8,Cleveland Cavaliers,2024-12-11,4.418143,2024-25,NaN
9,Cleveland Cavaliers,2024-12-16,4.538598,2024-25,NaN
10,Cleveland Cavaliers,2024-12-21,5.921790,2024-25,NaN
11,Cleveland Cavaliers,2024-12-26,6.729618,2024-25,NaN
12,Cleveland Cavaliers,2024-12-31,6.260155,2024-25,NaN
13,Cleveland Cavaliers,2025-01-05,6.034816,2024-25,NaN
14,Cleveland Cavaliers,2025-01-10,5.268779,2024-25,NaN
15,Cleveland Cavaliers,2025-01-15,3.702693,2024-25,NaN
16,Cleveland Cavaliers,2025-01-20,3.148878,2024-25,NaN
17,Cleveland Cavaliers,2025-01-25,2.649621,2024-25,NaN
18,Cleveland Cavaliers,2025-01-30,4.213353,2024-25,NaN
19,Cleveland Cavaliers,2025-02-04,5.981999,2024-25,NaN
20,Cleveland Cavaliers,2025-02-09,4.994950,2024-25,NaN
21,Cleveland Cavaliers,2025-02-14,5.407884,2024-25,NaN
22,Cleveland Cavaliers,2025-02-19,5.429167,2024-25,NaN
23,Cleveland Cavaliers,2025-02-24,NaN,2024-25,NaN
24,Cleveland Cavaliers,2025-03-01,NaN,2024-25,NaN